language: python
dist: xenial
group: travis_latest
services:
  - mysql
  - postgresql
addons:
# Use postgresql 9.3+ to get commit-lock testing;
# RelStorage works best on/dropped support for,
# older PG
  postgresql: "9.6"
python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7
  - pypy
  - pypy3
env:
  global:
    - ENV=travis
    - PYTHONHASHSEED=42
    - PYTHONPATH=.travis
    - Z_FAST="--processes 1 --loops 1 --values 1 --warmups 0 --object-counts 100"
    - Z_RUN="coverage run .travis/cover.py"
# We can test each one separately, but it
# uses less build jobs in total to run them together
# which is overall a bit faster.
    #- ENV=mysql
    #- ENV=postgres
    #- ENV=file
matrix:
  fast_finish: true
before_script:
  # Coverage is very slow on PyPy. 2 minutes for CPython, more than 8 for pypy
  - if [[ $TRAVIS_PYTHON_VERSION == pypy* ]]; Z_RUN="zodbshootout"; fi
script:
  - python -m zodbshootout --help
  - coverage run -m zope.testrunner --test-path=src --auto-color --auto-progress
  - $Z_RUN $Z_FAST -c 1 .travis/$ENV.conf --btrees --min-objects 100
  - $Z_RUN $Z_FAST -c 3 .travis/$ENV.conf --min-objects 200 --threads --gevent -o /tmp/f.json
  - $Z_RUN $Z_FAST -c 3 --blobs .travis/$ENV.conf --threads
after_success:
  - coverage combine
  - coveralls
notifications:
  email: false

install:
  - pip install -U pip setuptools
  - pip install -U coveralls coverage
  - pip install -U "gevent>=1.5a1"
  - pip install -U -e .[test]
  - .travis/setup-$ENV.sh

cache: pip

before_cache:
    - rm -f $HOME/.cache/pip/log/debug.log
